[colors.bright]
black = "#555555"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#0000aa"
cyan = "#00aaaa"
green = "#00aa00"
magenta = "#aa00aa"
red = "#aa0000"
white = "#aaaaaa"
yellow = "#aaaa00"

[colors.primary]
background = "#000000"
bright_foreground = "#ffffff"
dim_foreground = "#555555"
foreground = "#aaaaaa"

[cursor]
style = "Underline"

[font]
size = 7.0

[font.bold]
family = "Flexi IBM VGA False"

[font.bold_italic]
family = "Flexi IBM VGA False"

[font.italic]
family = "Flexi IBM VGA False"

[font.normal]
family = "Flexi IBM VGA False"

[window]
dynamic_padding = true
